export type PhoneCountryCodeEntry = {
  code: string
  labelEn: string
  labelZh: string
}

export const WORLD_PHONE_COUNTRY_CODES: PhoneCountryCodeEntry[] = [
  { code: "+93", labelEn: "Afghanistan", labelZh: "阿富汗" },
  { code: "+355", labelEn: "Albania", labelZh: "阿爾巴尼亞" },
  { code: "+213", labelEn: "Algeria", labelZh: "阿爾及利亞" },
  { code: "+1", labelEn: "American Samoa / Anguilla / Antigua and Barbuda / Bahamas / Barbados / Bermuda / British Virgin Islands / Canada / Cayman Islands / Dominica / Dominican Republic / Grenada / Guam / Jamaica / Montserrat / Puerto Rico / Saint Kitts and Nevis / Saint Lucia / Saint Vincent and the Grenadines / Trinidad and Tobago / Turks and Caicos Islands / United States / Virgin Islands (US)", labelZh: "美屬薩摩亞 / 安圭拉 / 安提瓜和巴布達 / 巴哈馬 / 巴巴多斯 / 百慕達 / 英屬維爾京群島 / 加拿大 / 開曼群島 / 多米尼克 / 多米尼加 / 格林納達 / 關島 / 牙買加 / 蒙特塞拉特 / 波多黎各 / 聖基茨和尼維斯 / 聖盧西亞 / 聖文森特和格林納丁斯 / 特立尼達和多巴哥 / 特克斯和凱科斯群島 / 美國 / 美屬維爾京群島" },
  { code: "+376", labelEn: "Andorra", labelZh: "安道爾" },
  { code: "+244", labelEn: "Angola", labelZh: "安哥拉" },
  { code: "+54", labelEn: "Argentina", labelZh: "阿根廷" },
  { code: "+374", labelEn: "Armenia", labelZh: "亞美尼亞" },
  { code: "+297", labelEn: "Aruba", labelZh: "阿魯巴" },
  { code: "+61", labelEn: "Australia", labelZh: "澳洲" },
  { code: "+43", labelEn: "Austria", labelZh: "奧地利" },
  { code: "+994", labelEn: "Azerbaijan", labelZh: "阿塞拜疆" },
  { code: "+973", labelEn: "Bahrain", labelZh: "巴林" },
  { code: "+880", labelEn: "Bangladesh", labelZh: "孟加拉" },
  { code: "+375", labelEn: "Belarus", labelZh: "白俄羅斯" },
  { code: "+32", labelEn: "Belgium", labelZh: "比利時" },
  { code: "+501", labelEn: "Belize", labelZh: "伯利茲" },
  { code: "+229", labelEn: "Benin", labelZh: "貝寧" },
  { code: "+975", labelEn: "Bhutan", labelZh: "不丹" },
  { code: "+591", labelEn: "Bolivia", labelZh: "玻利維亞" },
  { code: "+387", labelEn: "Bosnia and Herzegovina", labelZh: "波斯尼亞和黑塞哥維那" },
  { code: "+267", labelEn: "Botswana", labelZh: "博茨瓦納" },
  { code: "+55", labelEn: "Brazil", labelZh: "巴西" },
  { code: "+673", labelEn: "Brunei", labelZh: "文萊" },
  { code: "+359", labelEn: "Bulgaria", labelZh: "保加利亞" },
  { code: "+226", labelEn: "Burkina Faso", labelZh: "布基納法索" },
  { code: "+257", labelEn: "Burundi", labelZh: "布隆迪" },
  { code: "+855", labelEn: "Cambodia", labelZh: "柬埔寨" },
  { code: "+237", labelEn: "Cameroon", labelZh: "喀麥隆" },
  { code: "+238", labelEn: "Cape Verde", labelZh: "佛得角" },
  { code: "+236", labelEn: "Central African Republic", labelZh: "中非共和國" },
  { code: "+235", labelEn: "Chad", labelZh: "乍得" },
  { code: "+56", labelEn: "Chile", labelZh: "智利" },
  { code: "+86", labelEn: "China", labelZh: "中國" },
  { code: "+57", labelEn: "Colombia", labelZh: "哥倫比亞" },
  { code: "+269", labelEn: "Comoros", labelZh: "科摩羅" },
  { code: "+242", labelEn: "Congo", labelZh: "剛果" },
  { code: "+243", labelEn: "Congo (DRC)", labelZh: "剛果民主共和國" },
  { code: "+682", labelEn: "Cook Islands", labelZh: "庫克群島" },
  { code: "+506", labelEn: "Costa Rica", labelZh: "哥斯達黎加" },
  { code: "+385", labelEn: "Croatia", labelZh: "克羅地亞" },
  { code: "+53", labelEn: "Cuba", labelZh: "古巴" },
  { code: "+357", labelEn: "Cyprus", labelZh: "塞浦路斯" },
  { code: "+420", labelEn: "Czech Republic", labelZh: "捷克" },
  { code: "+45", labelEn: "Denmark", labelZh: "丹麥" },
  { code: "+253", labelEn: "Djibouti", labelZh: "吉布提" },
  { code: "+593", labelEn: "Ecuador", labelZh: "厄瓜多爾" },
  { code: "+20", labelEn: "Egypt", labelZh: "埃及" },
  { code: "+503", labelEn: "El Salvador", labelZh: "薩爾瓦多" },
  { code: "+240", labelEn: "Equatorial Guinea", labelZh: "赤道幾內亞" },
  { code: "+291", labelEn: "Eritrea", labelZh: "厄立特里亞" },
  { code: "+372", labelEn: "Estonia", labelZh: "愛沙尼亞" },
  { code: "+268", labelEn: "Eswatini", labelZh: "斯威士蘭" },
  { code: "+251", labelEn: "Ethiopia", labelZh: "埃塞俄比亞" },
  { code: "+500", labelEn: "Falkland Islands", labelZh: "福克蘭群島" },
  { code: "+298", labelEn: "Faroe Islands", labelZh: "法羅群島" },
  { code: "+679", labelEn: "Fiji", labelZh: "斐濟" },
  { code: "+358", labelEn: "Finland", labelZh: "芬蘭" },
  { code: "+33", labelEn: "France", labelZh: "法國" },
  { code: "+594", labelEn: "French Guiana", labelZh: "法屬圭亞那" },
  { code: "+689", labelEn: "French Polynesia", labelZh: "法屬波利尼西亞" },
  { code: "+241", labelEn: "Gabon", labelZh: "加蓬" },
  { code: "+220", labelEn: "Gambia", labelZh: "岡比亞" },
  { code: "+995", labelEn: "Georgia", labelZh: "格魯吉亞" },
  { code: "+49", labelEn: "Germany", labelZh: "德國" },
  { code: "+233", labelEn: "Ghana", labelZh: "加納" },
  { code: "+350", labelEn: "Gibraltar", labelZh: "直布羅陀" },
  { code: "+30", labelEn: "Greece", labelZh: "希臘" },
  { code: "+299", labelEn: "Greenland", labelZh: "格陵蘭" },
  { code: "+590", labelEn: "Guadeloupe", labelZh: "瓜德羅普" },
  { code: "+502", labelEn: "Guatemala", labelZh: "危地馬拉" },
  { code: "+224", labelEn: "Guinea", labelZh: "幾內亞" },
  { code: "+245", labelEn: "Guinea-Bissau", labelZh: "幾內亞比紹" },
  { code: "+592", labelEn: "Guyana", labelZh: "圭亞那" },
  { code: "+509", labelEn: "Haiti", labelZh: "海地" },
  { code: "+504", labelEn: "Honduras", labelZh: "洪都拉斯" },
  { code: "+852", labelEn: "Hong Kong", labelZh: "香港" },
  { code: "+36", labelEn: "Hungary", labelZh: "匈牙利" },
  { code: "+354", labelEn: "Iceland", labelZh: "冰島" },
  { code: "+91", labelEn: "India", labelZh: "印度" },
  { code: "+62", labelEn: "Indonesia", labelZh: "印尼" },
  { code: "+98", labelEn: "Iran", labelZh: "伊朗" },
  { code: "+964", labelEn: "Iraq", labelZh: "伊拉克" },
  { code: "+353", labelEn: "Ireland", labelZh: "愛爾蘭" },
  { code: "+972", labelEn: "Israel", labelZh: "以色列" },
  { code: "+39", labelEn: "Italy", labelZh: "意大利" },
  { code: "+225", labelEn: "Ivory Coast", labelZh: "科特迪瓦" },
  { code: "+81", labelEn: "Japan", labelZh: "日本" },
  { code: "+962", labelEn: "Jordan", labelZh: "約旦" },
  { code: "+7", labelEn: "Kazakhstan / Russia", labelZh: "哈薩克斯坦 / 俄羅斯" },
  { code: "+254", labelEn: "Kenya", labelZh: "肯尼亞" },
  { code: "+686", labelEn: "Kiribati", labelZh: "基里巴斯" },
  { code: "+965", labelEn: "Kuwait", labelZh: "科威特" },
  { code: "+996", labelEn: "Kyrgyzstan", labelZh: "吉爾吉斯" },
  { code: "+856", labelEn: "Laos", labelZh: "老撾" },
  { code: "+371", labelEn: "Latvia", labelZh: "拉脫維亞" },
  { code: "+961", labelEn: "Lebanon", labelZh: "黎巴嫩" },
  { code: "+266", labelEn: "Lesotho", labelZh: "萊索托" },
  { code: "+231", labelEn: "Liberia", labelZh: "利比里亞" },
  { code: "+218", labelEn: "Libya", labelZh: "利比亞" },
  { code: "+423", labelEn: "Liechtenstein", labelZh: "列支敦士登" },
  { code: "+370", labelEn: "Lithuania", labelZh: "立陶宛" },
  { code: "+352", labelEn: "Luxembourg", labelZh: "盧森堡" },
  { code: "+853", labelEn: "Macau", labelZh: "澳門" },
  { code: "+261", labelEn: "Madagascar", labelZh: "馬達加斯加" },
  { code: "+265", labelEn: "Malawi", labelZh: "馬拉維" },
  { code: "+60", labelEn: "Malaysia", labelZh: "馬來西亞" },
  { code: "+960", labelEn: "Maldives", labelZh: "馬爾代夫" },
  { code: "+223", labelEn: "Mali", labelZh: "馬里" },
  { code: "+356", labelEn: "Malta", labelZh: "馬耳他" },
  { code: "+692", labelEn: "Marshall Islands", labelZh: "馬紹爾群島" },
  { code: "+596", labelEn: "Martinique", labelZh: "馬提尼克" },
  { code: "+222", labelEn: "Mauritania", labelZh: "毛里塔尼亞" },
  { code: "+230", labelEn: "Mauritius", labelZh: "毛里求斯" },
  { code: "+262", labelEn: "Mayotte / Reunion", labelZh: "馬約特 / 留尼汪" },
  { code: "+52", labelEn: "Mexico", labelZh: "墨西哥" },
  { code: "+691", labelEn: "Micronesia", labelZh: "密克羅尼西亞" },
  { code: "+373", labelEn: "Moldova", labelZh: "摩爾多瓦" },
  { code: "+377", labelEn: "Monaco", labelZh: "摩納哥" },
  { code: "+976", labelEn: "Mongolia", labelZh: "蒙古" },
  { code: "+382", labelEn: "Montenegro", labelZh: "黑山" },
  { code: "+212", labelEn: "Morocco", labelZh: "摩洛哥" },
  { code: "+258", labelEn: "Mozambique", labelZh: "莫桑比克" },
  { code: "+95", labelEn: "Myanmar", labelZh: "緬甸" },
  { code: "+264", labelEn: "Namibia", labelZh: "納米比亞" },
  { code: "+674", labelEn: "Nauru", labelZh: "瑙魯" },
  { code: "+977", labelEn: "Nepal", labelZh: "尼泊爾" },
  { code: "+31", labelEn: "Netherlands", labelZh: "荷蘭" },
  { code: "+687", labelEn: "New Caledonia", labelZh: "新喀里多尼亞" },
  { code: "+64", labelEn: "New Zealand", labelZh: "紐西蘭" },
  { code: "+505", labelEn: "Nicaragua", labelZh: "尼加拉瓜" },
  { code: "+227", labelEn: "Niger", labelZh: "尼日爾" },
  { code: "+234", labelEn: "Nigeria", labelZh: "尼日利亞" },
  { code: "+683", labelEn: "Niue", labelZh: "紐埃" },
  { code: "+850", labelEn: "North Korea", labelZh: "北韓" },
  { code: "+389", labelEn: "North Macedonia", labelZh: "北馬其頓" },
  { code: "+47", labelEn: "Norway", labelZh: "挪威" },
  { code: "+968", labelEn: "Oman", labelZh: "阿曼" },
  { code: "+92", labelEn: "Pakistan", labelZh: "巴基斯坦" },
  { code: "+680", labelEn: "Palau", labelZh: "帕勞" },
  { code: "+970", labelEn: "Palestine", labelZh: "巴勒斯坦" },
  { code: "+507", labelEn: "Panama", labelZh: "巴拿馬" },
  { code: "+675", labelEn: "Papua New Guinea", labelZh: "巴布亞新幾內亞" },
  { code: "+595", labelEn: "Paraguay", labelZh: "巴拉圭" },
  { code: "+51", labelEn: "Peru", labelZh: "秘魯" },
  { code: "+63", labelEn: "Philippines", labelZh: "菲律賓" },
  { code: "+48", labelEn: "Poland", labelZh: "波蘭" },
  { code: "+351", labelEn: "Portugal", labelZh: "葡萄牙" },
  { code: "+974", labelEn: "Qatar", labelZh: "卡塔爾" },
  { code: "+40", labelEn: "Romania", labelZh: "羅馬尼亞" },
  { code: "+250", labelEn: "Rwanda", labelZh: "盧旺達" },
  { code: "+508", labelEn: "Saint Pierre and Miquelon", labelZh: "聖皮埃爾和密克隆" },
  { code: "+685", labelEn: "Samoa", labelZh: "薩摩亞" },
  { code: "+378", labelEn: "San Marino", labelZh: "聖馬力諾" },
  { code: "+239", labelEn: "Sao Tome and Principe", labelZh: "聖多美和普林西比" },
  { code: "+966", labelEn: "Saudi Arabia", labelZh: "沙特阿拉伯" },
  { code: "+221", labelEn: "Senegal", labelZh: "塞內加爾" },
  { code: "+381", labelEn: "Serbia", labelZh: "塞爾維亞" },
  { code: "+248", labelEn: "Seychelles", labelZh: "塞舌爾" },
  { code: "+232", labelEn: "Sierra Leone", labelZh: "塞拉利昂" },
  { code: "+65", labelEn: "Singapore", labelZh: "新加坡" },
  { code: "+421", labelEn: "Slovakia", labelZh: "斯洛伐克" },
  { code: "+386", labelEn: "Slovenia", labelZh: "斯洛文尼亞" },
  { code: "+677", labelEn: "Solomon Islands", labelZh: "所羅門群島" },
  { code: "+252", labelEn: "Somalia", labelZh: "索馬里" },
  { code: "+27", labelEn: "South Africa", labelZh: "南非" },
  { code: "+82", labelEn: "South Korea", labelZh: "韓國" },
  { code: "+211", labelEn: "South Sudan", labelZh: "南蘇丹" },
  { code: "+34", labelEn: "Spain", labelZh: "西班牙" },
  { code: "+94", labelEn: "Sri Lanka", labelZh: "斯里蘭卡" },
  { code: "+249", labelEn: "Sudan", labelZh: "蘇丹" },
  { code: "+597", labelEn: "Suriname", labelZh: "蘇里南" },
  { code: "+46", labelEn: "Sweden", labelZh: "瑞典" },
  { code: "+41", labelEn: "Switzerland", labelZh: "瑞士" },
  { code: "+963", labelEn: "Syria", labelZh: "敘利亞" },
  { code: "+886", labelEn: "Taiwan", labelZh: "台灣" },
  { code: "+992", labelEn: "Tajikistan", labelZh: "塔吉克斯坦" },
  { code: "+255", labelEn: "Tanzania", labelZh: "坦桑尼亞" },
  { code: "+66", labelEn: "Thailand", labelZh: "泰國" },
  { code: "+670", labelEn: "Timor-Leste", labelZh: "東帝汶" },
  { code: "+228", labelEn: "Togo", labelZh: "多哥" },
  { code: "+690", labelEn: "Tokelau", labelZh: "托克勞" },
  { code: "+676", labelEn: "Tonga", labelZh: "湯加" },
  { code: "+216", labelEn: "Tunisia", labelZh: "突尼斯" },
  { code: "+90", labelEn: "Turkey", labelZh: "土耳其" },
  { code: "+993", labelEn: "Turkmenistan", labelZh: "土庫曼斯坦" },
  { code: "+688", labelEn: "Tuvalu", labelZh: "圖瓦盧" },
  { code: "+256", labelEn: "Uganda", labelZh: "烏干達" },
  { code: "+380", labelEn: "Ukraine", labelZh: "烏克蘭" },
  { code: "+971", labelEn: "United Arab Emirates", labelZh: "阿聯酋" },
  { code: "+44", labelEn: "United Kingdom", labelZh: "英國" },
  { code: "+598", labelEn: "Uruguay", labelZh: "烏拉圭" },
  { code: "+998", labelEn: "Uzbekistan", labelZh: "烏茲別克" },
  { code: "+678", labelEn: "Vanuatu", labelZh: "瓦努阿圖" },
  { code: "+379", labelEn: "Vatican City", labelZh: "梵蒂岡" },
  { code: "+58", labelEn: "Venezuela", labelZh: "委內瑞拉" },
  { code: "+84", labelEn: "Vietnam", labelZh: "越南" },
  { code: "+681", labelEn: "Wallis and Futuna", labelZh: "瓦利斯和富圖納" },
  { code: "+967", labelEn: "Yemen", labelZh: "也門" },
  { code: "+260", labelEn: "Zambia", labelZh: "贊比亞" },
  { code: "+263", labelEn: "Zimbabwe", labelZh: "津巴布韋" },
]
